"""added confirmed atribute for user model

Revision ID: 0aaa8c6ed15b
Revises: aeb6e8b7b76b
Create Date: 2016-12-30 11:51:38.116499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaa8c6ed15b'
down_revision = 'aeb6e8b7b76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
